#define HintSilencerWotmod "com.14th_ua.hint_silencer_2.0.0.wotmod"
#define HintSilencerIdPrefix "com.14th_ua.hint_silencer"
#define ClassIconsWotmod "com.14th_ua.class-icons-recolor_0.1.0.wotmod"
#define ClassIconsIdPrefix "com.14th_ua.class-icons-recolor"
#define NeutralReticleWotmod "com.14th_ua.neutral-reticle_0.1.0.wotmod"
#define NeutralReticleIdPrefix "com.14th_ua.neutral-reticle"
#define UaRenameWotmod "com.14th_ua.super_secret_mod_1.0.0.wotmod"
#define UaRenameIdPrefix "com.14th_ua.super_secret_mod"
